modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="shiny_material"
version="0.3"
displayName="Shiny Material"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Morganischkalt"
description='''
Shiny Material for Minecraft
'''

[[dependencies.shiny_material]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




